// src/components/login.vue
<template>
    <div class="login_page">

    <section id="wrapper">
        <div class="login-register"  v-bind:style="{ 'background-image': 'url(' + bg + ')' }">

            <div class="login-box card">
                <div class="card-body">
                    <form class="form-horizontal form-material" id="loginform" action="index.html" novalidate @submit.prevent="LoginAuth" :validator="$v.form">
                        <h3 class="box-title m-b-20">Sign In</h3>
                        <div class="alert alert-danger" v-if="loginError">Invalid login id or password</div>
                        <div class="form-group ">
                            <div class="col-xs-12">
                                <input class="form-control" type="text" placeholder="Username" v-model.trim="name" @click="$v.name.$touch()">
                                 <p class="error-message" v-if="!$v.name.required && $v.name.$dirty">Please Enter Userid</p>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="password" placeholder="Password"  v-model.trim="password" @click="$v.password.$touch()"> </div>
                                <p class="error-message" v-if="!$v.password.required && $v.password.$dirty">Please Enter Password</p>

                        </div>
                      
                        <div class="form-group text-center m-t-20">
                            <div class="col-xs-12">
                                <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit" :disabled="$v.$invalid">Log In</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </section>
    </div>
</template>

<script>
var image = require("@/assets/images/background/login.jpg");
import Vue from 'vue';
import Vuelidate from 'vuelidate'
import { required } from 'vuelidate/lib/validators'
import {LoginService} from '../api/auth';
import {EncryptionModule} from '../api/excryptionservice';
import router from '../routes';
import $ from 'jquery';
Vue.use(Vuelidate)
export default {
  name: "Login",
  data() {
    return {
    bg: image,
    name:'',
    password:'',
    loginError:false
    };
  },
  methods:{
     LoginAuth()
     {   $('.preloader').css('display','block');
         var data={user_email:this.name, password:this.password, 'role_id': 1}
         this.name='';
         this.password='';
         this.$v.$reset();
         LoginService.LoginAuth(data).then(response=>{

             $('.preloader').css('display','none');
            if(response.status==200)
            {   var records= response.data.data;
                localStorage.setItem('user_id', records.user_id);
                localStorage.setItem('loginStatus', EncryptionModule.EncryptionService('LoggedIn1'));
                router.push('/home');
            }
            else{
                this.loginError=true;
                setTimeout(()=>{
                    this.loginError=false;
                },3000);
            }
         }).catch(e=>{
             $('.preloader').css('display','none');
             throw e;
         })
     }
  },
  validations:{
      name:{
          required,
      },
      password:{
          required
      }
  }
};
</script>

<style scoped>
    .error-message
    {
        font-size: 12px;
        color: red;
    }
</style>

// src/app/authentication/login/login.component.ts
import { Component, OnInit, AfterViewInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { EncryptionService } from '../../services/encryption.service';
import { Validators, FormGroup, FormBuilder } from '@angular/forms';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers: [EncryptionService]

})
export class LoginComponent implements OnInit, AfterViewInit {
  LoginForm: FormGroup;
  constructor(public router: Router,
    private AuthService: AuthService,
    private EncryptionService: EncryptionService,
    private fb: FormBuilder
  ) {}

  ngOnInit() {

    this.LoginFormInit();
    
    var status = this.EncryptionService.DecryptText(localStorage.getItem('loginStatus'));



    if (status == "LoggedIn1") {
      this.router.navigate(['/campaign']);
      return false;
    }

    return true;
  
}

ngAfterViewInit() {
  $(function() {
    $(".preloader").fadeOut();
  });
  $(function() {
    ( < any > $('[data-toggle="tooltip"]')).tooltip()
  });
  $('#to-recover').on("click", function() {
    $("#loginform").slideUp();
    $("#recoverform").fadeIn();
  });
}



UserData: any = [];
ErrorMsg: boolean = false;

// Login authentication
LoginAuth(formData) {
  
  let data = {
    'user_email': formData.value.user_email,
    'password': formData.value.password,
    'role_id': 1
  };

  this.LoginFormInit();
  this.AuthService.LoginAuth(data).subscribe(res => {
    if (res.status == 200) {


      localStorage.setItem('loginStatus', this.EncryptionService.EncryptText('LoggedIn1'));
      localStorage.setItem('user_id', res.data.user_id);
      // localStorage.setItem('user_name', this.EncryptionService.EncryptText(res.employeeData.user_name));
      this.router.navigate(['/campaign']);


    } else {
      this.ErrorMsg = true;
      setTimeout(() => { this.ErrorMsg = false; }, 3000);


    }
  }, err => {
    this.ErrorMsg = true;
    setTimeout(() => { this.ErrorMsg = false; }, 3000);


  });
}




// Set Login From

LoginFormInit() {
  this.LoginForm = this.fb.group({
    user_email: ['', Validators.compose([Validators.required])],
    password: ['', Validators.compose([Validators.required])],
  });
}

}

<div class="login-register" style="background-image:url(assets/images/background/login-register.jpg);">
  <div class="login-box card">
    <div class="card-body">
      <form class="form-horizontal form-material" [formGroup]="LoginForm" (ngSubmit)="LoginAuth(LoginForm)">
        <h3 class="box-title m-b-20">Sign In</h3>
        <div class="alert alert-danger" *ngIf="ErrorMsg==true"><i class="fa fa-times"></i> Invalid Username or password!</div> 
        <div class="form-group">
          <div class="col-xs-12">
            <input class="form-control" type="text" required="" placeholder="Username or email" formControlName="user_email"> 
            <div *ngIf="LoginForm.controls['user_email'].touched && !LoginForm.controls['user_email'].valid" class="has-danger">
              <small _ngcontent-c3="" class="form-control-feedback"> Please Enter Userid</small>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
            <input class="form-control" type="password" required="" placeholder="Password" formControlName="password">
            <div *ngIf="LoginForm.controls['password'].touched && !LoginForm.controls['password'].valid" class="has-danger">
              <small _ngcontent-c3="" class="form-control-feedback"> Please Enter Password</small>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-md-12 font-14">
            <div class="checkbox checkbox-primary pull-left p-t-0">
              <!-- <input id="checkbox-signup" type="checkbox"> -->
              <!-- <label for="checkbox-signup"> Remember me </label> -->
            </div>
          </div>
        </div>
        <div class="form-group text-center m-t-20">
          <div class="col-xs-12">
            <button class="btn btn-primary btn-round btn-lg btn-block" [disabled]="!LoginForm.valid">SIGN IN</button>
          </div>
          <!-- <a href="javascript:void(0)" id="to-recover" class="text-dark pull-right">Forgot password?</a> -->
        </div>
        
      </form>
      <form class="form-horizontal" id="recoverform" action="index.html">
        <div class="form-group ">
          <div class="col-xs-12">
            <h3>Recover Password</h3>
            <p class="text-muted">Enter your Email and instructions will be sent to you! </p>
          </div>
        </div>
        <div class="form-group ">
          <div class="col-xs-12">
            <input class="form-control" type="text" required="" placeholder="Email"> </div>
        </div>
        <div class="form-group text-center m-t-20">
          <div class="col-xs-12">
            <a class="btn btn-primary btn-lg btn-block text-uppercase waves-effect waves-light" [routerLink]="['/login']">Reset</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
